# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'sqlite3'
gem 'activerecord'
gem 'rspec'
gem 'pry'
gem 'sinatra-activerecord'
gem 'rake'
gem 'database_cleaner'
gem 'require_all'
gem 'tty-table'
