require_relative './config/environment'
require 'sinatra/activerecord/rake'

# Type `rake -T` on your command line to see the available rake tasks.

task :console do
  Pry.start
end


# get user info and save to user table
namespace :get_user_info
  desc "ask user for name, update user table"
  task :get_name do
  
    end
